# Generated by Django 5.0.4 on 2026-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies', max_length=300)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='LogMessage',
        ),
    ]
